import { Geist, Geist_Mono, Audiowide, Bruno_Ace } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
const audiowide = Audiowide({
  variable: "--font-audiowide",
  subsets: ['latin'],
  weight: '400'
});
const brunoace = Bruno_Ace({
  variable: "--font-brunoace",
  subsets: ['latin'],
  weight: '400'
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${audiowide.variable} ${brunoace.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
